serverJS:
	@cd hora; \
		node serv6.js

cliJS:
	cd hora; \
		node cli6.js

serverJS2:
	cd fichero; \
		node serv6.js

cliJS2:
	cd fichero; \
		node cli6.js $(path)

all:
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."
